# Generated by Django 3.0.8 on 2020-08-03 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departmental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('remark', models.TextField(blank=True, max_length=1000, null=True, verbose_name='備考')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
            options={
                'verbose_name_plural': '部署',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('remark', models.TextField(blank=True, max_length=1000, null=True, verbose_name='備考')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('departmental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_info.Departmental', verbose_name='部署')),
            ],
            options={
                'verbose_name_plural': 'スキル',
            },
        ),
    ]
