# Generated by Django 3.0.8 on 2020-08-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmental',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='departmental',
            name='create_user',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='departmental',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='departmental',
            name='update_user',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='更新者'),
        ),
        migrations.AddField(
            model_name='skill',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='skill',
            name='create_user',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='skill',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='skill',
            name='update_user',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='更新者'),
        ),
    ]
