# Generated by Django 3.0.8 on 2020-08-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office_info', '0003_auto_20200810_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='office_info.Task', verbose_name='タスク'),
        ),
    ]
