# Generated by Django 3.0.8 on 2020-08-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_info', '0004_skill_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='task',
        ),
        migrations.AddField(
            model_name='skill',
            name='task',
            field=models.ManyToManyField(related_name='skill', to='office_info.Task', verbose_name='タスク'),
        ),
    ]
