# Generated by Django 3.0.8 on 2020-08-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_info', '0006_auto_20200811_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskskill',
            name='name',
        ),
        migrations.AddField(
            model_name='taskskill',
            name='skill_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='スキル名称'),
        ),
        migrations.AlterField(
            model_name='taskskill',
            name='ratio',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='割合'),
        ),
    ]
