# Generated by Django 3.0.8 on 2020-08-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_info', '0007_auto_20200812_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskskill',
            name='ratio',
            field=models.IntegerField(blank=True, null=True, verbose_name='割合'),
        ),
    ]
