# Generated by Django 3.0.8 on 2020-08-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_info', '0009_auto_20200821_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='company_code',
            field=models.CharField(max_length=10, verbose_name='社員コード'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment',
            field=models.CharField(max_length=20, verbose_name='雇用'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment_insurance_number',
            field=models.CharField(max_length=11, verbose_name='雇用保険番号'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='health_insurance_number',
            field=models.CharField(max_length=8, verbose_name='健康保険番号'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='携帯電話'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='my_number',
            field=models.CharField(max_length=12, verbose_name='マイナンバー'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position_name',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='役職'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='職種'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(max_length=6, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='自宅'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='zip_code',
            field=models.CharField(max_length=7, verbose_name='郵便番号'),
        ),
    ]
