# Generated by Django 3.0.8 on 2020-08-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office_info', '0010_auto_20200821_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='departmental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='office_info.Departmental', verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='役職'),
        ),
    ]
